name: {{ snakeCase name }}
description: A new Flutter package project.
version: 0.0.1
homepage: "www.concord.com.br"
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  {{ snakeCase name }}_package_a:
    path: {{ snakeCase name }}_package_a

  {{ snakeCase name }}_package_b:
    path: {{ snakeCase name }}_package_b

dev_dependencies:
  flutter_test:
    sdk: flutter
