name: concord_arch
description: A new Flutter package project.
version: 0.0.1
homepage: "www.concord.com.br"
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  concord_foundation:
    path: ../concord_foundation

  bloc: 8.0.2
  flutter_bloc: 8.0.1
  
  navigation:
    path: navigation

dev_dependencies:
  flutter_test:
    sdk: flutter
