name: concord_foundation
description: A new Flutter package project.
version: 0.0.1
homepage: "www.concord.com.br"
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  di:
    path: di

  exceptions:
    path: exceptions

  flutter:
    sdk: flutter

  serialization:
    path: serialization
  
  types:
    path: types

dev_dependencies:
  flutter_test:
    sdk: flutter
