name: concord_foundation
description: A new Flutter package project.
version: 0.0.1
author: "concord"
homepage: "www.concord.com.br"
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  base_exceptions:
    path: base_exceptions

  di:
    path: di

  flutter:
    sdk: flutter

  helper_types:
    path: helper_types

  type_extensions:
    path: type_extensions

dev_dependencies:
  flutter_test:
    sdk: flutter
