name: {{ snakeCase name }}_playground
description: A new Flutter package project.
version: 0.0.1
homepage: "www.{{ snakeCase $org }}.com.br"
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  playground:
    path: ../../../{{ snakeCase $org }}_ui/playground

  {{ snakeCase name }}:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
