name: global_library
description: A new Flutter package project.
version: 0.0.1
homepage: "www.concord.com.br"
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  scaffold_library:
    path: ../scaffold_library

  token_library:
    path: ../token_library
    
dev_dependencies:
  flutter_test:
    sdk: flutter
