name: auth
description: A new Flutter package project.
version: 0.0.1
author: "concord"
homepage: "www.concord.com.br"
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  concord_foundation:
    path: ../../concord_foundation
  
  firebase_auth: 3.3.4

  flutter:
    sdk: flutter

  networking:
    path: ../networking

  shared_models:
    path: ../shared_models

dev_dependencies:
  flutter_test:
    sdk: flutter
