name: auth
description: A new Flutter package project.
version: 0.0.1
homepage: "www.concord.com.br"
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  concord_foundation:
    path: ../../concord_foundation
  
  firebase_auth: 3.3.4

  flutter:
    sdk: flutter

  networking:
    path: ../networking

  shared_models:
    path: ../shared_models

dev_dependencies:
  build_runner: 2.1.7

  flutter_test:
    sdk: flutter

  freezed: 1.1.0
  json_serializable: 6.1.3
