name: {{ snakeCase name }}
description: A new Flutter package project.
version: 0.0.1
author: "{{ $org }}"
homepage: "www.{{ $org }}.com.br"
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  {{ $org }}_arch:
    path: ../../{{ $org }}_arch

  {{ $org }}_core:
    path: ../../{{ $org }}_core

  {{ $org }}_ui:
    path: ../../{{ $org }}_ui

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
