name: {{ snakeCase name }}
description: A new Flutter package project.
version: 0.0.1
homepage: "www.{{ $org }}.com.br"
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  {{ $org }}_arch:
    path: ../../{{ $org }}_arch

  {{ $org }}_foundation:
    path: ../../{{ $org }}_foundation

  {{ snakeCase name }}_data:
    path: {{ snakeCase name }}_data

  {{ snakeCase name }}_team_library:
    path: {{ snakeCase name }}_team_library

dev_dependencies:
  build_runner: 2.1.7

  flutter_test:
    sdk: flutter

  freezed: 1.1.0
  json_serializable: 6.1.3
