name: {{ snakeCase name }}
description: A new Flutter package project.
version: 0.0.1
author: "{{ $org }}"
homepage: "www.{{ $org }}.com.br"
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  {{ $org }}_arch:
    path: ../../{{ $org }}_arch

  {{ $org }}_ui:
    path: ../../{{ $org }}_ui

  flutter:
    sdk: flutter

  shared_models:
    path: ../../{{ $org }}_common/shared_models

dev_dependencies:
  flutter_test:
    sdk: flutter
