name: concord_ui
description: A new Flutter package project.
version: 0.0.1
homepage: "www.concord.com.br"
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  loading_indicator: 3.0.2

  serialization:
    git:
      url: git@github.com:viniciusaro/concord.git
      path: concord-app/concord_foundation/serialization
      ref: master
  
dev_dependencies:
  flutter_test:
    sdk: flutter
