name: concord_ui
description: A new Flutter package project.
version: 0.0.1
homepage: "www.concord.com.br"
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  global_library:
    path: global_library

  networking:
    path: ../concord_core/networking
  
  scaffold_library:
    path: scaffold_library

  storage:
    path: ../concord_core/storage

  token_library:
    path: token_library

dev_dependencies:
  flutter_test:
    sdk: flutter
