name: tokens_v_2
description: A new Flutter package project.
version: 0.0.1
homepage: "www.concord.com.br"
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  serialization:
    git:
      url: git@github.com:viniciusaro/concord.git
      path: concord-app/concord_foundation/serialization
      ref: master
    
  tokens:
    git:
      url: git@github.com:viniciusaro/concord.git
      path: concord/concord-app/concord_ui/tokens
      ref: master

dev_dependencies:
  build_runner: 2.1.7

  flutter_test:
    sdk: flutter

  freezed: 1.1.0
  json_serializable: 6.1.3
