name: chat
description: A new Flutter package project.
version: 0.0.1
author: "concord"
homepage: "www.concord.com.br"
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  chat_data:
    path: data

  concord_arch:
    path: ../../concord_arch

  flutter:
    sdk: flutter

  shared_models:
    path: ../../concord_common/shared_models

  team_library:
    path: team_library

dev_dependencies:
  flutter_test:
    sdk: flutter
