name: concord_core
description: A new Flutter package project.
version: 0.0.1
homepage: "www.concord.com.br"
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  auth:
    path: auth

  concord_foundation:
    path: ../concord_foundation

  flutter:
    sdk: flutter

  networking:
    path: networking

  shared_models:
    path: shared_models

  storage:
    path: storage

dev_dependencies:
  flutter_test:
    sdk: flutter
